nome = str(input('Digite seu nome completo: ')).strip()
print('Analizando o seu nome... ')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minuúsculas é {}'.format(nome.lower()))
print('seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
#print('O seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('O seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
